import { ScreensManager } from '@micromag/core';
import article from '@micromag/screen-article';
import audio from '@micromag/screen-audio';
import contribution from '@micromag/screen-contribution';
import conversation from '@micromag/screen-conversation';
import gallery from '@micromag/screen-gallery';
import galleryFeed from '@micromag/screen-gallery-feed';
import image from '@micromag/screen-image';
import keypad from '@micromag/screen-keypad';
import map from '@micromag/screen-map';
import quiz from '@micromag/screen-quiz';
import quote from '@micromag/screen-quote';
import ranking from '@micromag/screen-ranking';
import share from '@micromag/screen-share';
import slideshow from '@micromag/screen-slideshow';
import survey from '@micromag/screen-survey';
import text from '@micromag/screen-text';
import timeline from '@micromag/screen-timeline';
import title from '@micromag/screen-title';
import urbaniaArticle, {
    definitionCard as urbaniaArticleCard,
} from '@micromag/screen-urbania-article';
import urbaniaHoroscope from '@micromag/screen-urbania-horoscope';
import urbaniaRecommendation from '@micromag/screen-urbania-recommendation';
import urbaniaTrivia from '@micromag/screen-urbania-trivia';
import video from '@micromag/screen-video';
import video360 from '@micromag/screen-video-360';

const manager = new ScreensManager();
manager.addDefinition(article);
manager.addDefinition(audio);
manager.addDefinition(contribution);
manager.addDefinition(conversation);
manager.addDefinition(gallery);
manager.addDefinition(galleryFeed);
manager.addDefinition(keypad);
manager.addDefinition(image);
manager.addDefinition(map);
manager.addDefinition(quiz);
manager.addDefinition(quote);
manager.addDefinition(ranking);
manager.addDefinition(share);
manager.addDefinition(survey);
manager.addDefinition(text);
manager.addDefinition(timeline);
manager.addDefinition(title);
manager.addDefinition(video);
manager.addDefinition(video360);
manager.addDefinition(slideshow);
manager.addDefinition(urbaniaArticle);
manager.addDefinition(urbaniaArticleCard);
manager.addDefinition(urbaniaTrivia);
manager.addDefinition(urbaniaRecommendation);
manager.addDefinition(urbaniaHoroscope);

export default manager;
