import resolve from '@rollup/plugin-node-resolve';

import { createConfig } from '../../rollup.config.mjs';

export default [
    // createConfig({
    //     file: 'index.js',
    //     format: 'cjs',
    // }),
    createConfig({
        input: 'src/bin/export.ts',
        output: 'bin/export.js',
        banner: '#!/usr/bin/env node',
        format: 'node',
        prependPlugins: [
            resolve({
                resolveOnly: [
                    'query-string',
                    'wouter',
                    'exifr',
                    'nanoid',
                    'gsap',
                    'd3',
                    'screenfull',
                    'split-on-first',
                    'filter-obj',
                    'decode-uri-component',
                    'supports-webp',
                    'use-supercluster',
                    'supercluster',
                    'kdbush',
                    'react-focus-lock',
                    'internmap',
                    'flatqueue',
                    /date-fns/,
                    /[a-z]+-case/,
                    /@folklore/,
                    /@micromag/,
                    /@uppy/,
                    /@mui/,
                    /@emotion/,
                    /d3/,
                    /@panneau/,
                    /@babel\/runtime/,
                    '@builder.io/react-hydration-overlay',
                    'react-diff-viewer',
                ],
            }),
            resolve({
                exportConditions: ['node'],
                modulesOnly: true,
                resolveOnly: [
                    'query-string',
                    'wouter',
                    'exifr',
                    'nanoid',
                    'gsap',
                    'd3',
                    'screenfull',
                    'split-on-first',
                    'filter-obj',
                    'decode-uri-component',
                    'supports-webp',
                    'use-supercluster',
                    'supercluster',
                    'kdbush',
                    'react-focus-lock',
                    'internmap',
                    'flatqueue',
                    /date-fns/,
                    /[a-z]+-case/,
                    /@folklore/,
                    /@micromag/,
                    /@uppy/,
                    /@mui/,
                    /@emotion/,
                    /d3/,
                    /@panneau/,
                    /@babel\/runtime/,
                    '@builder.io/react-hydration-overlay',
                    'react-diff-viewer',
                ],
            }),
        ],
    }),
];
